FinalProject/Models/Invoice.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.InvoiceLineItems = new HashSet<InvoiceLineItem>();
        }
    
        public int InvoiceID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal ProductTotal { get; set; }
        public decimal SalesTax { get; set; }
        public decimal Shipping { get; set; }
        public decimal InvoiceTotal { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<InvoiceLineItem> InvoiceLineItems { get; set; }
    }
}

FinalProject/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using System.Data.Entity.Migrations;

namespace FinalProject.Controllers
{
    public class InvoiceController : Controller
    {
        // GET: Invoice
        public ActionResult All(string id, int sortBy = 0)
        {
            Entities context = new Entities();
            List<Invoice> allInvoices = context.Invoices.ToList<Invoice>();
            switch (sortBy)
            {
                case 0:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.InvoiceID).ToList();
                        break;
                    }
                case 1:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.CustomerID).ToList();
                        break;
                    }
                case 2:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.InvoiceDate).ToList();
                        break;
                    }
                case 3:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.ProductTotal).ToList();
                        break;
                    }
                case 4:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.SalesTax).ToList();
                        break;
                    }
                case 5:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.Shipping).ToList();
                        break;
                    }
                case 6:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.InvoiceTotal).ToList();
                        break;
                    }
                case 7:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.InvoiceLineItems.Count).ToList();
                        break;
                    }
                default:
                    {
                        allInvoices = context.Invoices.OrderBy(i => i.InvoiceID).ToList();
                        break;
                    }
            }
                    return View(allInvoices);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">This is the ID of the invoice.</param>
        /// <returns>The view to the website.</returns>
        [HttpGet]
        public ActionResult Upsert(int id = 0)
        {
            Entities context = new Entities();
            Invoice newInvoice = context.Invoices.Where(i => i.InvoiceID == id).FirstOrDefault();
            if (newInvoice == null)
            {
                newInvoice = new Invoice();
                newInvoice.Customer = new Customer();
            }
            InvoiceDTO dto = new InvoiceDTO()
            {
                Invoice = newInvoice,
                Customers = context.Customers.ToList(),
                Products = context.Products.ToList()
            };
            return View(dto);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="invoiceModel">This is the invoice DTO model.</param>
        /// <param name="customerId">Customer ID that is a string then it's converted to an int.</param>
        /// <returns>Redirects back to main page.</returns>
        [HttpPost]
        public ActionResult Upsert(InvoiceDTO invoiceModel, string customerId)
        {
            Entities context = new Entities();
            int iCustomerID = Convert.ToInt32(customerId.Split('-')[0].Trim());
            invoiceModel.Invoice.CustomerID = iCustomerID;
            Invoice invoiceToUpdate = CalculateInvoiceTotals(invoiceModel.Invoice);
            try
            {
                context.Invoices.AddOrUpdate(invoiceModel.Invoice);
            }
            catch (Exception ex)
            {

                throw ex;
            }
            context.SaveChanges();
            return RedirectToAction("All");
        }
        /// <summary>
        /// This method calculates the invoice totals using a foreach loop.
        /// </summary>
        /// <param name="invoice">This is used to grab an invoice.</param>
        /// <returns>An invoice.</returns>
        public Invoice CalculateInvoiceTotals(Invoice invoice)
        {
            Entities context = new Entities();

            List<InvoiceLineItem> lineItems = context.InvoiceLineItems.Where(i => i.InvoiceID == invoice.InvoiceID).ToList();

            invoice.InvoiceTotal = 0;
            invoice.ProductTotal = 0;
            foreach (var lineItem in lineItems)
            {
                invoice.ProductTotal = invoice.ProductTotal + lineItem.ItemTotal;
            }
            invoice.InvoiceTotal = invoice.ProductTotal + invoice.Shipping + invoice.SalesTax;

            return invoice;
        }
    }
}

FinalProject/Views/Invoice/All.cshtml
@model List<FinalProject.Models.Invoice>
@{
    ViewBag.Title = "All";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Invoices</h2>
<div class="row">
    <div class="col-md-6">
        <input id="txtsearch" style="text" class="form-control" onkeyup="search();" placeholder="Search..." /><br />
        <input type="button" class="btn btn-info" value="search" onclick="search();" />
    </div>
</div>
<a href="/Invoice/Upsert/0">Add Invoice Data</a>

<table class="sortable table table-hover">
    <thead>
        <tr>
            <th onclick="Sortable.Sort(0);">Invoice ID</th>
            <th onclick="Sortable.Sort(1);">Customer ID</th>
            <th onclick="Sortable.Sort(2);">Invoice Date</th>
            <th onclick="Sortable.Sort(3);">Product Total</th>
            <th onclick="Sortable.Sort(4);">Sales Tax</th>
            <th onclick="Sortable.Sort(5);">Shipping</th>
            <th onclick="Sortable.Sort(6);">Total</th>
            <th onclick="Sortable.Sort(7);">Total Line Items</th>
            <th>Edit</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var invoice in Model)
        {
        <tr>
            <td>@invoice.InvoiceID</td>
            <td>@invoice.CustomerID</td>
            <td>@invoice.InvoiceDate</td>
            <td>$@invoice.ProductTotal</td>
            <td>$@invoice.SalesTax</td>
            <td>$@invoice.Shipping</td>
            <td>$@invoice.InvoiceTotal</td>
            <td>@invoice.InvoiceLineItems.Count</td>


            <td><a href="/Invoice/Upsert/@invoice.InvoiceID">Edit</a></td>
        </tr>
        }
    </tbody>
    @*

            public int InvoiceID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal ProductTotal { get; set; }
        public decimal SalesTax { get; set; }
        public decimal Shipping { get; set; }
        public decimal InvoiceTotal { get; set; }*@
</table>
<script>
    Sortable.baseUrl = "/Invoice/All/";
</script>

FinalProject/Views/Invoice/Upsert.cshtml
@model FinalProject.Models.InvoiceDTO
@{
    ViewBag.Title = "Upsert an Invoice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upsert an invoice</h2>

@using (Html.BeginForm("Upsert", "Invoice", FormMethod.Post))
{
    @Html.HiddenFor(i => i.Invoice.InvoiceID);
    <span>Customer Id:</span>
    <input value="@Model.Invoice.CustomerID - @Model.Invoice.Customer.Name" type="text" list="customersList" class="form-control" name="customerId" />
    <datalist id="customersList">
        @foreach (var customer in Model.Customers)
        {
            <option value="@customer.CustomerID - @customer.Name" />
        }
    </datalist>
    <span>Invoice Date:</span>
    @Html.TextBoxFor(i => i.Invoice.InvoiceDate, new { @class = "form-control" })
    <span>Product Total:</span>
    <input value="@Model.Invoice.ProductTotal" type="text" readonly class="form-control" name="Invoice.ProductTotal" />
    <span>Sales Tax:</span>
    @Html.TextBoxFor(i => i.Invoice.SalesTax, new { @class = "form-control" })
    <span>Shipping Tax</span>
    @Html.TextBoxFor(i => i.Invoice.Shipping, new { @class = "form-control" })
    <span>Invoice Total:</span>
    <input value="@Model.Invoice.InvoiceTotal" type="text" readonly class="form-control" name="Invoice.InvoiceTotal" />

    <button type="submit" class="btn">Save Invoice</button>
}
<hr />
<h4>Invoice Line Items Section</h4>
<a href="/InvoiceLineItems/Upsert/?invoiceId=@Model.Invoice.InvoiceID&productCode=0">Add new Line Item</a>

<datalist id="products">
    @foreach (var product in Model.Products)
    {
        <option value="@product.ProductCode"></option>
    }
</datalist>
@foreach (var lineItem in Model.Invoice.InvoiceLineItems)
{
    <input type="hidden" name="InvoiceID" value="@lineItem.InvoiceID" />
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <span>Product Code</span>
                </div>
                <div class="col-md-6">
                    <input name="ProductCode" list="products" readonly value="@lineItem.ProductCode" type="text" class="form-control" />
                </div>
            </div>
            <a href="/InvoiceLineItems/Upsert/?invoiceId=@lineItem.InvoiceID&productCode=@lineItem.ProductCode">Edit</a>

        </div>
    </div>
}