FinalProject/Models/InvoiceLineItem.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLineItem
    {
        public int InvoiceID { get; set; }
        public string ProductCode { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal ItemTotal { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual Product Product { get; set; }
    }
}

FinalProject/Controllers/InvoiceLineItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using System.Data.Entity.Migrations;

namespace FinalProject.Controllers
{
    public class InvoiceLineItemsController : Controller
    {
        /// <summary>
        /// This grabs the line item from the url.
        /// </summary>
        /// <param name="invoiceId">InvoiceID for the line item.</param>
        /// <param name="productCode">productCode for the line item.</param>
        /// <returns>The line Item and puts it on the page.</returns>
        [HttpGet]
        public ActionResult Upsert(int invoiceId, string productCode)
        {
            Entities context = new Entities();

            InvoiceLineItem lineItem = context.InvoiceLineItems.Where(i => i.InvoiceID == invoiceId && i.ProductCode == productCode).FirstOrDefault();
            if (lineItem == null)
            {
                lineItem = new InvoiceLineItem();
                lineItem.InvoiceID = invoiceId;
            }

            List<Product> newProducts = context.Products.ToList();
            LineItemDTO UC = new LineItemDTO()
            {
                LineItem = lineItem,
                Products = newProducts
            };
            return View(UC);
        }
        /// <summary>
        /// This method is used to post a LineItem to the invoice.
        /// 
        /// </summary>
        /// <param name="lineItem">The line item itself.</param>
        /// <returns>Back to the invoice page.</returns>
        [HttpPost]
        public ActionResult Upsert(LineItemDTO model, string ProductCode)
        {
            InvoiceLineItem lineItem = model.LineItem;
            lineItem.ProductCode = ProductCode.Trim();
            Entities context = new Entities();
            try
            {
                lineItem.ItemTotal = lineItem.Quantity * lineItem.UnitPrice; 
                context.InvoiceLineItems.AddOrUpdate(lineItem);
                context.SaveChanges();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Redirect("/Invoice/Upsert/" + lineItem.InvoiceID.ToString());
        }
    }
}

FinalProject/Views/InvoiceLineItems/Upsert.cshtml
@model FinalProject.Models.LineItemDTO
@{
    ViewBag.Title = "Upsert Invoice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upsert Invoice Line Item</h2>

@using (Html.BeginForm("Upsert", "InvoiceLineItems", FormMethod.Post))
{
    @Html.HiddenFor(i => i.LineItem.InvoiceID)
    <input value="@Model.LineItem.ProductCode" type="text" list="productList" class="form-control" name="ProductCode" />
    <datalist id="productList">
        @foreach (var product in Model.Products)
        {
            <option value="@product.ProductCode" />
        }
    </datalist>
    <span>UnitPrice</span>@Html.TextBoxFor(i => i.LineItem.UnitPrice)
    <span>Quantity</span>@Html.TextBoxFor(i => i.LineItem.Quantity)
    <button type="submit">Submit</button>


}