FinalProject/Models/State.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public string StateCode { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}

FinalProject/Controllers/StateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using System.Data.Entity.Migrations;


public class StateController : Controller
    {
        // GET: State
        public ActionResult All(string id, int sortBy = 0)
        {
            Entities context = new Entities();
            List<State> allStates;
            switch (sortBy)
            {
                case 0:
                    {
                    allStates = context.States.OrderBy(i => i.StateName).ToList();
                        break;
                    }
                case 1:
                    {
                    allStates = context.States.OrderBy(i => i.StateCode).ToList();
                        break;
                    }
                default:
                    {
                    allStates = context.States.OrderBy(i => i.StateName).ToList();
                        break;
                    }
            }
            return View(allStates);
        }
    [HttpGet]
    public ActionResult Upsert(string id)
    {
        Entities context = new Entities();
        State newState = context.States.Where(p => p.StateCode == id).FirstOrDefault();
        if (newState == null)
        {
            newState = new State();
            newState.StateCode = "zz";
        }

        List<State> newStates = context.States.ToList();
        return View(newState);
    }
    [HttpPost]
    public ActionResult Upsert(State StateModel)
    {
        Entities context = new Entities();
        try
        {
            context.States.AddOrUpdate(StateModel);
        }
        catch (Exception ex)
        {

            throw ex;
        }
        context.SaveChanges();
        return RedirectToAction("All");
    }
}

FinalProject/Views/State/All.cshtml
@model List<FinalProject.Models.State>
@{
    ViewBag.Title = "All";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of States</h2>
<div class="row">
    <div class="col-md-6">
        <input id="txtsearch" style="text" class="form-control" onkeyup="search();" placeholder="Search..." /><br />
        <input type="button" class="btn btn-info" value="search" onclick="search();" />
    </div>
</div>
<a href="/State/Upsert/zz">Add State Data</a>

<table class="sortable table table-hover">
    <thead>
        <tr>
            <th onclick="Sortable.Sort(0);">State Code</th>
            <th onclick="Sortable.Sort(1);">State Name</th>
            <th>Edit</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var state in Model)
        {
            <tr>
                <td>@state.StateCode</td>
                <td>@state.StateName</td>
                <td><a href="/State/Upsert/@state.StateCode">Edit</a></td>
            </tr>
        }
    </tbody>
</table>
<script>
    Sortable.baseUrl = "/State/All/";
</script>

FinalProject/Views/State/Upsert.cshtml
@model FinalProject.Models.State
@{
    ViewBag.Title = "Upsert State";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upsert State</h2>

@using (Html.BeginForm("Upsert", "State", FormMethod.Post))
{
    <span>State Code</span>@Html.TextBoxFor(i => i.StateCode)
    <span>State Name</span>@Html.TextBoxFor(i => i.StateName)
    <button type="submit">Submit</button>
}